import React from "react";

export const AboutUs = () =>{
    return(
        <>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        <h1>About US</h1>
        </>
    )
}